### PR TITLE
add fixer, Fixes #46

### LINKED ISSUE #46: autofix
Can you add autofix flag support.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
```js
return Object.assign({a}, value, { cookie });
```

becomes

```js
return ({ ...({a}), ...(value), ...({ cookie }) });
```

you need to use other rules to remove the useless rest spread, and extra parentheses.

**Comment by graingert** [comment]
@bryanrsmith tests are passing but it looks like there's a problem with your coverage config.

**Comment by bryanrsmith** [comment]
Thanks, @graingert! This is great. I will take a look at the coverage configuration.

Can you help me understand the issue with inserting useless spreads and extra parens? As it stands, the fixed code is, in my opinion, less ideal than the original Object.assign code. I'd prefer not to support fixing unless it can produce clean output.

**Comment by graingert** [comment]
@bryanrsmith I've fixed it so:

```js
return Object.assign({}, value, { cookie });
```

becomes

```js
return ({...(value), ...({ cookie }) });
```

It's only the case where the object has properties, that it inserts a useless rest spread.

**Comment by graingert** [comment]
It's ok to depend on the [no-useless-spread](https://github.com/mysticatea/eslint-plugin/blob/master/docs/rules/no-useless-rest-spread.md) and [no-extra-parens](http://eslint.org/docs/rules/no-extra-parens) rules for further changes:

From [the docs](http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) emphasis mine:

> 1.  Avoid any fixes that could change the runtime behavior of code and
>     cause it to stop working.
> 2.  **Make fixes as small as possible**. Fixes that are unnecessarily
>     large could conflict with other fixes, and prevent them from
>     being applied.
> 3.  Only make one fix per message. This is enforced because you must
>     return the result of the fixer operation from
>     `fix()`{.highlighter-rouge}.
> 4.  Since all rules are run again after the initial round of fixes is
>     applied, **it’s not necessary for a rule to check whether the code
>     style of a fix will cause errors to be reported by another rule.**
>     -   For example, suppose a fixer would like to surround an object
>         key with quotes, but it’s not sure whether the user would
>         prefer single or double quotes.
>
>         <div class="language-js highlighter-rouge">
>
>         ``` {.highlight}
>           ({ foo : 1 })
>
>           // should get fixed to either
>
>           ({ 'foo': 1 })
>
>           // or
>
>           ({ "foo": 1 })
>         ```
>
>         </div>
>
>     -   This fixer can just select a quote type arbitrarily. If it
>         guesses wrong, the resulting code will be automatically
>         reported and fixed by the
>         [`quotes`{.highlighter-rouge}](/docs/rules/quotes) rule.
>

**Comment by bryanrsmith** [comment]
Sorry, but I don't want the fixer to rely on another plugin to reach an acceptable result.

`return Object.assign({}, value, { cookie });`

should fix to

`return {...value, cookie};`

Is there a reason not to do this? It seems like we'd only need to inspect each argument node type. Object literals would get their properties expanded into the parent object, and everything else would get spread to the parent object. The inserted parens seem unnecessary-- maybe except for `SequenceExpression`s?

**Comment by bryanrsmith** [comment]
I've pushed a change to `master` that fixes the coverage. Thanks for pointing that out!

**Comment by graingert** [comment]
We need the outer parens because:
```js
() => Object.assign({}, value, { cookie });
```
needs to become:

```js
() => ({ ...value, ...{ cookie });
```

But where those extra parens are not needed, they will be removed by the no-extra-parens plugin.

**Comment by bryanrsmith** [comment]
Ok, sounds reasonable. `no-useless-spread` is not a core rule, though. I think we need to avoid unnecessary spreads.

**Comment by graingert** [comment]
Once rest/spread properties are in stage-4 it will probably become a core rule.

@bryanrsmith we could merge this whole plugin into https://github.com/mysticatea/eslint-plugin/ if @mysticatea were up for it.

**Comment by graingert** [comment]
@bryanrsmith actually I've determined that the parenthesis inside the object spread aren't needed.

**Comment by bryanrsmith** [comment]
Ok. I'd still prefer not to generate unnecessary spreads, but I think we can start with this and maybe improve that later. If you could please fix the inconsistent indentation so it's using tabs I'll merge.

**Comment by AlanFoster** [comment]
An autofixer would be great! Any progress updates to this? :+1:

**Comment by graingert** [comment]
@AlanFoster I wrote this code, ran it on my codebase then forgot about it. I recommend you manually install it as you only need to run it once per codebase

**Comment by bryanrsmith** [comment]
I was waiting to merge because of some inconsistent formatting, but I'd like to make some changes to code formatting in this project anyways. Thanks @graingert!

**Comment by graingert** [comment]
@bryanrsmith might be worth switching to https://www.npmjs.com/package/eslint-config-eslint for when we want to merge this into core.

**Comment by bryanrsmith** [comment]
Released as v1.2.1.

**Pull request merged**
